In [1]:
import pandas as pd

c:\Users\MehdiMoghadam\anaconda3\lib\site-packages\pandas\core\computation\expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.8.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
c:\Users\MehdiMoghadam\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [16]:
country_df = pd.read_csv(r'C:\Users\MehdiMoghadam\OneDrive - Agilysis Limited\Desktop\Data Collector\FastAPI\Vechain\countries.csv')
iso_df = pd.read_csv(r'C:\Users\MehdiMoghadam\OneDrive - Agilysis Limited\Desktop\Data Collector\FastAPI\Vechain\country-code-to-currency-code-mapping.csv')
iso_df

,Country,CountryCode,Currency,Code
0,New Zealand,NZ,New Zealand Dollars,NZD
1,Cook Islands,CK,New Zealand Dollars,NZD
2,Niue,NU,New Zealand Dollars,NZD
3,Pitcairn,PN,New Zealand Dollars,NZD
4,Tokelau,TK,New Zealand Dollars,NZD
...,...,...,...,...
245,Saint Helena,SH,Saint Helena pound,GBP
246,Saint Martin (French part),MF,Netherlands Antillean guilder,ANG
247,Saint Pierre and Miquelon,PM,Euro,EUR
248,Serbia,RS,Serbian dinar,RSD
249,US Armed Forces,USAF,US Dollar,USD

In [15]:
country = {}

for i in range(len(country_df)):
    country[f'{country_df.iloc[i,1]}'] = country_df.iloc[i,0]
    
country

{'Andorra': 'AD',
 'United Arab Emirates': 'AE',
 'Afghanistan': 'AF',
 'Antigua and Barbuda': 'AG',
 'Anguilla': 'AI',
 'Albania': 'AL',
 'Armenia': 'AM',
 'Angola': 'AO',
 'Antarctica': 'AQ',
 'Argentina': 'AR',
 'American Samoa': 'AS',
 'Austria': 'AT',
 'Australia': 'AU',
 'Aruba': 'AW',
 'Aland Islands': 'AX',
 'Azerbaijan': 'AZ',
 'Bosnia and Herzegovina': 'BA',
 'Barbados': 'BB',
 'Bangladesh': 'BD',
 'Belgium': 'BE',
 'Burkina Faso': 'BF',
 'Bulgaria': 'BG',
 'Bahrain': 'BH',
 'Burundi': 'BI',
 'Benin': 'BJ',
 'Saint Barthelemy': 'BL',
 'Bermuda': 'BM',
 'Brunei': 'BN',
 'Bolivia': 'BO',
 'Bonaire, Saint Eustatius and Saba': 'BQ',
 'Brazil': 'BR',
 'Bahamas': 'BS',
 'Bhutan': 'BT',
 'Bouvet Island': 'BV',
 'Botswana': 'BW',
 'Belarus': 'BY',
 'Belize': 'BZ',
 'Canada': 'CA',
 'Cocos Islands': 'CC',
 'Democratic Republic of the Congo': 'CD',
 'Central African Republic': 'CF',
 'Republic of the Congo': 'CG',
 'Switzerland': 'CH',
 'Ivory Coast': 'CI',
 'Cook Islands': 'CK',
 'Chile': 'CL',
 'Cameroon': 'CM',
 'China': 'CN',
 'Colombia': 'CO',
 'Costa Rica': 'CR',
 'Cuba': 'CU',
 'Cabo Verde': 'CV',
 'Curacao': 'CW',
 'Christmas Island': 'CX',
 'Cyprus': 'CY',
 'Czechia': 'CZ',
 'Germany': 'DE',
 'Djibouti': 'DJ',
 'Denmark': 'DK',
 'Dominica': 'DM',
 'Dominican Republic': 'DO',
 'Algeria': 'DZ',
 'Ecuador': 'EC',
 'Estonia': 'EE',
 'Egypt': 'EG',
 'Western Sahara': 'EH',
 'Eritrea': 'ER',
 'Spain': 'ES',
 'Ethiopia': 'ET',
 'Finland': 'FI',
 'Fiji': 'FJ',
 'Falkland Islands': 'FK',
 'Micronesia': 'FM',
 'Faroe Islands': 'FO',
 'France': 'FR',
 'Gabon': 'GA',
 'United Kingdom': 'GB',
 'Grenada': 'GD',
 'Georgia': 'GE',
 'French Guiana': 'GF',
 'Guernsey': 'GG',
 'Ghana': 'GH',
 'Gibraltar': 'GI',
 'Greenland': 'GL',
 'Gambia': 'GM',
 'Guinea': 'GN',
 'Guadeloupe': 'GP',
 'Equatorial Guinea': 'GQ',
 'Greece': 'GR',
 'South Georgia and the South Sandwich Islands': 'GS',
 'Guatemala': 'GT',
 'Guam': 'GU',
 'Guinea-Bissau': 'GW',
 'Guyana': 'GY',
 'Hong Kong': 'HK',
 'Heard Island and McDonald Islands': 'HM',
 'Honduras': 'HN',
 'Croatia': 'HR',
 'Haiti': 'HT',
 'Hungary': 'HU',
 'Indonesia': 'ID',
 'Ireland': 'IE',
 'Israel': 'IL',
 'Isle of Man': 'IM',
 'India': 'IN',
 'British Indian Ocean Territory': 'IO',
 'Iraq': 'IQ',
 'Iran': 'IR',
 'Iceland': 'IS',
 'Italy': 'IT',
 'Jersey': 'JE',
 'Jamaica': 'JM',
 'Jordan': 'JO',
 'Japan': 'JP',
 'Kenya': 'KE',
 'Kyrgyzstan': 'KG',
 'Cambodia': 'KH',
 'Kiribati': 'KI',
 'Comoros': 'KM',
 'Saint Kitts and Nevis': 'KN',
 'North Korea': 'KP',
 'South Korea': 'KR',
 'Kuwait': 'KW',
 'Cayman Islands': 'KY',
 'Kazakhstan': 'KZ',
 'Laos': 'LA',
 'Lebanon': 'LB',
 'Saint Lucia': 'LC',
 'Liechtenstein': 'LI',
 'Sri Lanka': 'LK',
 'Liberia': 'LR',
 'Lesotho': 'LS',
 'Lithuania': 'LT',
 'Luxembourg': 'LU',
 'Latvia': 'LV',
 'Libya': 'LY',
 'Morocco': 'MA',
 'Monaco': 'MC',
 'Moldova': 'MD',
 'Montenegro': 'ME',
 'Saint Martin': 'MF',
 'Madagascar': 'MG',
 'Marshall Islands': 'MH',
 'North Macedonia': 'MK',
 'Mali': 'ML',
 'Myanmar': 'MM',
 'Mongolia': 'MN',
 'Macao': 'MO',
 'Northern Mariana Islands': 'MP',
 'Martinique': 'MQ',
 'Mauritania': 'MR',
 'Montserrat': 'MS',
 'Malta': 'MT',
 'Mauritius': 'MU',
 'Maldives': 'MV',
 'Malawi': 'MW',
 'Mexico': 'MX',
 'Malaysia': 'MY',
 'Mozambique': 'MZ',
 'Namibia': nan,
 'New Caledonia': 'NC',
 'Niger': 'NE',
 'Norfolk Island': 'NF',
 'Nigeria': 'NG',
 'Nicaragua': 'NI',
 'Netherlands': 'NL',
 'Norway': 'NO',
 'Nepal': 'NP',
 'Nauru': 'NR',
 'Niue': 'NU',
 'New Zealand': 'NZ',
 'Oman': 'OM',
 'Panama': 'PA',
 'Peru': 'PE',
 'French Polynesia': 'PF',
 'Papua New Guinea': 'PG',
 'Philippines': 'PH',
 'Pakistan': 'PK',
 'Poland': 'PL',
 'Saint Pierre and Miquelon': 'PM',
 'Pitcairn': 'PN',
 'Puerto Rico': 'PR',
 'Palestinian Territory': 'PS',
 'Portugal': 'PT',
 'Palau': 'PW',
 'Paraguay': 'PY',
 'Qatar': 'QA',
 'Reunion': 'RE',
 'Romania': 'RO',
 'Serbia': 'RS',
 'Russia': 'RU',
 'Rwanda': 'RW',
 'Saudi Arabia': 'SA',
 'Solomon Islands': 'SB',
 'Seychelles': 'SC',
 'Sudan': 'SD',
 'Sweden': 'SE',
 'Singapore': 'SG',
 'Saint Helena': 'SH',
 'Slovenia': 'SI',
 'Svalbard and Jan Mayen': 'SJ',
 'Slovakia': 'SK',
 'Sierra Leone': 'SL',
 'San Marino': 'SM',
 'Senegal': 'SN',
 'Somalia': 'SO',
 'Suriname': 'SR',
 'South Sudan': 'SS',
 'Sao Tome and Principe': 'ST',
 'El Salvador': 'SV',
 'Sint Maarten': 'SX',
 'Syria': 'SY',
 'Eswatini': 'SZ',
 'Turks and Caicos Islands': 'TC',
 'Chad': 'TD',
 'French Southern Territories': 'TF',
 'Togo': 'TG',
 'Thailand': 'TH',
 'Tajikistan': 'TJ',
 'Tokelau': 'TK',
 'Timor Leste': 'TL',
 'Turkmenistan': 'TM',
 'Tunisia': 'TN',
 'Tonga': 'TO',
 'Turkey': 'TR',
 'Trinidad and Tobago': 'TT',
 'Tuvalu': 'TV',
 'Taiwan': 'TW',
 'Tanzania': 'TZ',
 'Ukraine': 'UA',
 'Uganda': 'UG',
 'United States Minor Outlying Islands': 'UM',
 'United States': 'US',
 'Uruguay': 'UY',
 'Uzbekistan': 'UZ',
 'Vatican': 'VA',
 'Saint Vincent and the Grenadines': 'VC',
 'Venezuela': 'VE',
 'British Virgin Islands': 'VG',
 'U.S. Virgin Islands': 'VI',
 'Vietnam': 'VN',
 'Vanuatu': 'VU',
 'Wallis and Futuna': 'WF',
 'Samoa': 'WS',
 'Yemen': 'YE',
 'Mayotte': 'YT',
 'South Africa': 'ZA',
 'Zambia': 'ZM',
 'Zimbabwe': 'ZW'}

In [17]:
iso = {}

for i in range(len(iso_df)):
    iso[f'{iso_df.iloc[i,1]}'] = iso_df.iloc[i,3]
    
iso

{'NZ': 'NZD',
 'CK': 'NZD',
 'NU': 'NZD',
 'PN': 'NZD',
 'TK': 'NZD',
 'AU': 'AUD',
 'CX': 'AUD',
 'CC': 'AUD',
 'HM': 'AUD',
 'KI': 'AUD',
 'NR': 'AUD',
 'NF': 'AUD',
 'TV': 'AUD',
 'AS': 'EUR',
 'AD': 'EUR',
 'AT': 'EUR',
 'BE': 'EUR',
 'FI': 'EUR',
 'FR': 'EUR',
 'GF': 'EUR',
 'TF': 'EUR',
 'DE': 'EUR',
 'GR': 'EUR',
 'GP': 'EUR',
 'IE': 'EUR',
 'IT': 'EUR',
 'LU': 'EUR',
 'MQ': 'EUR',
 'YT': 'EUR',
 'MC': 'EUR',
 'NL': 'EUR',
 'PT': 'EUR',
 'RE': 'EUR',
 'WS': 'EUR',
 'SM': 'EUR',
 'SI': 'EUR',
 'ES': 'EUR',
 'VA': 'EUR',
 'GS': 'GBP',
 'GB': 'GBP',
 'JE': 'GBP',
 'IO': 'USD',
 'GU': 'USD',
 'MH': 'USD',
 'FM': 'USD',
 'MP': 'USD',
 'PW': 'USD',
 'PR': 'USD',
 'TC': 'USD',
 'US': 'USD',
 'UM': 'USD',
 'VG': 'USD',
 'VI': 'USD',
 'HK': 'HKD',
 'CA': 'CAD',
 'JP': 'JPY',
 'AF': 'AFN',
 'AL': 'ALL',
 'DZ': 'DZD',
 'AI': 'XCD',
 'AG': 'XCD',
 'DM': 'XCD',
 'GD': 'XCD',
 'MS': 'XCD',
 'KN': 'XCD',
 'LC': 'XCD',
 'VC': 'XCD',
 'AR': 'ARS',
 'AM': 'AMD',
 'AW': 'ANG',
 'AN': 'ANG',
 'AZ': 'AZN',
 'BS': 'BSD',
 'BH': 'BHD',
 'BD': 'BDT',
 'BB': 'BBD',
 'BY': 'BYR',
 'BZ': 'BZD',
 'BJ': 'XOF',
 'BF': 'XOF',
 'GW': 'XOF',
 'CI': 'XOF',
 'ML': 'XOF',
 'NE': 'XOF',
 'SN': 'XOF',
 'TG': 'XOF',
 'BM': 'BMD',
 'BT': 'INR',
 'IN': 'INR',
 'BO': 'BOB',
 'BW': 'BWP',
 'BV': 'NOK',
 'NO': 'NOK',
 'SJ': 'NOK',
 'BR': 'BRL',
 'BN': 'BND',
 'BG': 'BGN',
 'BI': 'BIF',
 'KH': 'KHR',
 'CM': 'XAF',
 'CF': 'XAF',
 'TD': 'XAF',
 'CG': 'XAF',
 'GQ': 'XAF',
 'GA': 'XAF',
 'CV': 'CVE',
 'KY': 'KYD',
 'CL': 'CLP',
 'CN': 'CNY',
 'CO': 'COP',
 'KM': 'KMF',
 'CD': 'CDF',
 'CR': 'CRC',
 'HR': 'HRK',
 'CU': 'CUP',
 'CY': 'CYP',
 'CZ': 'CZK',
 'DK': 'DKK',
 'FO': 'DKK',
 'GL': 'DKK',
 'DJ': 'DJF',
 'DO': 'DOP',
 'TP': 'IDR',
 'ID': 'IDR',
 'EC': 'ECS',
 'EG': 'EGP',
 'SV': 'SVC',
 'ER': 'ETB',
 'ET': 'ETB',
 'EE': 'EEK',
 'FK': 'FKP',
 'FJ': 'FJD',
 'PF': 'XPF',
 'NC': 'XPF',
 'WF': 'XPF',
 'GM': 'GMD',
 'GE': 'GEL',
 'GI': 'GIP',
 'GT': 'GTQ',
 'GN': 'GNF',
 'GY': 'GYD',
 'HT': 'HTG',
 'HN': 'HNL',
 'HU': 'HUF',
 'IS': 'ISK',
 'IR': 'IRR',
 'IQ': 'IQD',
 'IL': 'ILS',
 'JM': 'JMD',
 'JO': 'JOD',
 'KZ': 'KZT',
 'KE': 'KES',
 'KP': 'KPW',
 'KR': 'KRW',
 'KW': 'KWD',
 'KG': 'KGS',
 'LA': 'LAK',
 'LV': 'LVL',
 'LB': 'LBP',
 'LS': 'LSL',
 'LR': 'LRD',
 'LY': 'LYD',
 'LI': 'CHF',
 'CH': 'CHF',
 'LT': 'LTL',
 'MO': 'MOP',
 'MK': 'MKD',
 'MG': 'MGA',
 'MW': 'MWK',
 'MY': 'MYR',
 'MV': 'MVR',
 'MT': 'MTL',
 'MR': 'MRO',
 'MU': 'MUR',
 'MX': 'MXN',
 'MD': 'MDL',
 'MN': 'MNT',
 'MA': 'MAD',
 'EH': 'MAD',
 'MZ': 'MZN',
 'MM': 'MMK',
 'nan': 'NAD',
 'NP': 'NPR',
 'NI': 'NIO',
 'NG': 'NGN',
 'OM': 'OMR',
 'PK': 'PKR',
 'PA': 'PAB',
 'PG': 'PGK',
 'PY': 'PYG',
 'PE': 'PEN',
 'PH': 'PHP',
 'PL': 'PLN',
 'QA': 'QAR',
 'RO': 'RON',
 'RU': 'RUB',
 'RW': 'RWF',
 'ST': 'STD',
 'SA': 'SAR',
 'SC': 'SCR',
 'SL': 'SLL',
 'SG': 'SGD',
 'SK': 'SKK',
 'SB': 'SBD',
 'SO': 'SOS',
 'ZA': 'ZAR',
 'LK': 'LKR',
 'SD': 'SDG',
 'SR': 'SRD',
 'SZ': 'SZL',
 'SE': 'SEK',
 'SY': 'SYP',
 'TW': 'TWD',
 'TJ': 'TJS',
 'TZ': 'TZS',
 'TH': 'THB',
 'TO': 'TOP',
 'TT': 'TTD',
 'TN': 'TND',
 'TR': 'TRY',
 'TM': 'TMT',
 'UG': 'UGX',
 'UA': 'UAH',
 'AE': 'AED',
 'UY': 'UYU',
 'UZ': 'UZS',
 'VU': 'VUV',
 'VE': 'VEF',
 'VN': 'VND',
 'YE': 'YER',
 'ZM': 'ZMK',
 'ZW': 'ZWD',
 'AX': 'EUR',
 'AO': 'AOA',
 'AQ': 'AQD',
 'BA': 'BAM',
 'GH': 'GHS',
 'GG': 'GGP',
 'IM': 'GBP',
 'ME': 'EUR',
 'PS': 'JOD',
 'BL': 'EUR',
 'SH': 'GBP',
 'MF': 'ANG',
 'PM': 'EUR',
 'RS': 'RSD',
 'USAF': 'USD'}

In [12]:
data = pd.read_csv(r'C:\Users\MehdiMoghadam\OneDrive - Agilysis Limited\Desktop\Data Collector\FastAPI\Vechain\main_carbon_data.csv')
data

,Unnamed: 0.1,Unnamed: 0,MCC Code,MCC Name,EXIOBASE Name,Network,Year,Unit,Andorra,United Arab Emirates,...,U.S. Virgin Islands,Vietnam,Vanuatu,Wallis and Futuna,Samoa,Yemen,Mayotte,South Africa,Zambia,Zimbabwe
0,0,0,742,Veterinary Services,Health and social work services (85),"Visa, Mastercard",2019,kgCO2e/â‚¬,0.047325,0.410842,...,0.168457,0.333657,0.333657,0.333657,0.333657,0.410842,0.507871,0.304124,0.507871,0.507871
1,1,1,763,Agricultural Co-operatives,Cereal grains nec,"Visa, Mastercard",2019,kgCO2e/â‚¬,1.472558,2.934405,...,1.516011,2.348465,2.348465,2.348465,2.348465,2.934405,2.528996,2.720207,2.528996,2.528996
2,2,2,780,Landscaping and Horticultural Services,Other services (93),"Visa, Mastercard",2019,kgCO2e/â‚¬,0.126395,1.153704,...,0.329961,0.528856,0.528856,0.528856,0.528856,1.153704,1.629691,0.797773,1.629691,1.629691
3,3,3,1520,General Contractors â€“ Residential and Commercial,Construction work (45),"Visa, Mastercard",2019,kgCO2e/â‚¬,0.240473,0.845016,...,0.654963,1.246178,1.246178,1.246178,1.246178,0.845016,1.201898,0.786338,1.201898,1.201898
4,4,4,1711,"Heating, Plumbing, and Air Conditioning Contra...",Construction work (45),"Visa, Mastercard",2019,kgCO2e/â‚¬,0.240473,0.845016,...,0.654963,1.246178,1.246178,1.246178,1.246178,0.845016,1.201898,0.786338,1.201898,1.201898
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,298,298,9402,Postal Services â€“ Government Only,Post and telecommunication services (64),"Visa, Mastercard",2019,kgCO2e/â‚¬,0.061473,0.242962,...,0.219076,0.389803,0.389803,0.389803,0.389803,0.242962,0.413403,0.217973,0.413403,0.413403
299,299,299,9405,U.S. Federal Government Agencies or Departments,Public administration and defence services; co...,"Visa, Mastercard",2019,kgCO2e/â‚¬,0.084661,0.223510,...,0.169341,0.685085,0.685085,0.685085,0.685085,0.223510,0.784261,0.147517,0.784261,0.784261
300,300,300,9406,Government-Owned Lotteries (Non-U.S. region),"Recreational, cultural and sporting services (92)","Visa, Mastercard",2019,kgCO2e/â‚¬,0.130112,0.394244,...,0.446235,0.513924,0.513924,0.513924,0.513924,0.394244,1.045093,0.443903,1.045093,1.045093
301,301,301,9702,Emergency Services (GCAS) (Visa use only),NaN,Visa,2019,kgCO2e/â‚¬,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
302,302,302,9950,Intra-Company Purchases,NaN,Visa,2019,kgCO2e/â‚¬,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [70]:
data.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'MCC Code', 'MCC Name', 'EXIOBASE Name',
       'Network', 'Year', 'Unit', 'Andorra', 'United Arab Emirates',
       ...
       'U.S. Virgin Islands', 'Vietnam', 'Vanuatu', 'Wallis and Futuna',
       'Samoa', 'Yemen', 'Mayotte', 'South Africa', 'Zambia', 'Zimbabwe'],
      dtype='object', length=257)

In [73]:
data[data['MCC Code']=='742']

,Unnamed: 0.1,Unnamed: 0,MCC Code,MCC Name,EXIOBASE Name,Network,Year,Unit,Andorra,United Arab Emirates,...,U.S. Virgin Islands,Vietnam,Vanuatu,Wallis and Futuna,Samoa,Yemen,Mayotte,South Africa,Zambia,Zimbabwe
0,0,0,742,Veterinary Services,Health and social work services (85),"Visa, Mastercard",2019,kgCO2e/â‚¬,0.047325,0.410842,...,0.168457,0.333657,0.333657,0.333657,0.333657,0.410842,0.507871,0.304124,0.507871,0.507871

In [106]:

data = pd.read_csv(r'C:\Users\MehdiMoghadam\OneDrive - Agilysis Limited\Desktop\Data Collector\FastAPI\Vechain\main_carbon_data.csv')
country_df = pd.read_csv(r'C:\Users\MehdiMoghadam\OneDrive - Agilysis Limited\Desktop\Data Collector\FastAPI\Vechain\countries.csv')
iso_df = pd.read_csv(r'C:\Users\MehdiMoghadam\OneDrive - Agilysis Limited\Desktop\Data Collector\FastAPI\Vechain\country-code-to-currency-code-mapping.csv')

import PyCurrency_Converter
country = {}
iso = {}
c = CurrencyConverter()


for i in range(len(country_df)):
    country[f'{country_df.iloc[i,1]}'] = country_df.iloc[i,0]
    
for i in range(len(iso_df)):
    iso[f'{iso_df.iloc[i,1]}'] = iso_df.iloc[i,3]
        


from datetime import date
from currency_converter import CurrencyConverter  # https://pypi.python.org/pypi/CurrencyConverter/
URL = 'https://raw.githubusercontent.com/AnotherKamila/currency-exchange-rates/master/rates.csv'
cc = CurrencyConverter(URL, ref_currency='USD')

def calculate_carbon(country_code, amount, df, country, iso, mcc):
    euro_amount = cc.convert(amount, iso[country[country_code]], 'EUR', date=date(2018, 1, 20))
    row = pd.DataFrame(df[df['MCC Code']==str(mcc)])[country_code]
    return euro_amount * row.to_list()[0]

In [107]:


calculate_carbon('United Arab Emirates', 200, data, country, iso,1711)

37.635523924461445

In [105]:
a

37.635523924461445

In [23]:
country_df['ISO Country Name'].to_list()

['Andorra',
 'United Arab Emirates',
 'Afghanistan',
 'Antigua and Barbuda',
 'Anguilla',
 'Albania',
 'Armenia',
 'Angola',
 'Antarctica',
 'Argentina',
 'American Samoa',
 'Austria',
 'Australia',
 'Aruba',
 'Aland Islands',
 'Azerbaijan',
 'Bosnia and Herzegovina',
 'Barbados',
 'Bangladesh',
 'Belgium',
 'Burkina Faso',
 'Bulgaria',
 'Bahrain',
 'Burundi',
 'Benin',
 'Saint Barthelemy',
 'Bermuda',
 'Brunei',
 'Bolivia',
 'Bonaire, Saint Eustatius and Saba',
 'Brazil',
 'Bahamas',
 'Bhutan',
 'Bouvet Island',
 'Botswana',
 'Belarus',
 'Belize',
 'Canada',
 'Cocos Islands',
 'Democratic Republic of the Congo',
 'Central African Republic',
 'Republic of the Congo',
 'Switzerland',
 'Ivory Coast',
 'Cook Islands',
 'Chile',
 'Cameroon',
 'China',
 'Colombia',
 'Costa Rica',
 'Cuba',
 'Cabo Verde',
 'Curacao',
 'Christmas Island',
 'Cyprus',
 'Czechia',
 'Germany',
 'Djibouti',
 'Denmark',
 'Dominica',
 'Dominican Republic',
 'Algeria',
 'Ecuador',
 'Estonia',
 'Egypt',
 'Western Sahara',
 'Eritrea',
 'Spain',
 'Ethiopia',
 'Finland',
 'Fiji',
 'Falkland Islands',
 'Micronesia',
 'Faroe Islands',
 'France',
 'Gabon',
 'United Kingdom',
 'Grenada',
 'Georgia',
 'French Guiana',
 'Guernsey',
 'Ghana',
 'Gibraltar',
 'Greenland',
 'Gambia',
 'Guinea',
 'Guadeloupe',
 'Equatorial Guinea',
 'Greece',
 'South Georgia and the South Sandwich Islands',
 'Guatemala',
 'Guam',
 'Guinea-Bissau',
 'Guyana',
 'Hong Kong',
 'Heard Island and McDonald Islands',
 'Honduras',
 'Croatia',
 'Haiti',
 'Hungary',
 'Indonesia',
 'Ireland',
 'Israel',
 'Isle of Man',
 'India',
 'British Indian Ocean Territory',
 'Iraq',
 'Iran',
 'Iceland',
 'Italy',
 'Jersey',
 'Jamaica',
 'Jordan',
 'Japan',
 'Kenya',
 'Kyrgyzstan',
 'Cambodia',
 'Kiribati',
 'Comoros',
 'Saint Kitts and Nevis',
 'North Korea',
 'South Korea',
 'Kuwait',
 'Cayman Islands',
 'Kazakhstan',
 'Laos',
 'Lebanon',
 'Saint Lucia',
 'Liechtenstein',
 'Sri Lanka',
 'Liberia',
 'Lesotho',
 'Lithuania',
 'Luxembourg',
 'Latvia',
 'Libya',
 'Morocco',
 'Monaco',
 'Moldova',
 'Montenegro',
 'Saint Martin',
 'Madagascar',
 'Marshall Islands',
 'North Macedonia',
 'Mali',
 'Myanmar',
 'Mongolia',
 'Macao',
 'Northern Mariana Islands',
 'Martinique',
 'Mauritania',
 'Montserrat',
 'Malta',
 'Mauritius',
 'Maldives',
 'Malawi',
 'Mexico',
 'Malaysia',
 'Mozambique',
 'Namibia',
 'New Caledonia',
 'Niger',
 'Norfolk Island',
 'Nigeria',
 'Nicaragua',
 'Netherlands',
 'Norway',
 'Nepal',
 'Nauru',
 'Niue',
 'New Zealand',
 'Oman',
 'Panama',
 'Peru',
 'French Polynesia',
 'Papua New Guinea',
 'Philippines',
 'Pakistan',
 'Poland',
 'Saint Pierre and Miquelon',
 'Pitcairn',
 'Puerto Rico',
 'Palestinian Territory',
 'Portugal',
 'Palau',
 'Paraguay',
 'Qatar',
 'Reunion',
 'Romania',
 'Serbia',
 'Russia',
 'Rwanda',
 'Saudi Arabia',
 'Solomon Islands',
 'Seychelles',
 'Sudan',
 'Sweden',
 'Singapore',
 'Saint Helena',
 'Slovenia',
 'Svalbard and Jan Mayen',
 'Slovakia',
 'Sierra Leone',
 'San Marino',
 'Senegal',
 'Somalia',
 'Suriname',
 'South Sudan',
 'Sao Tome and Principe',
 'El Salvador',
 'Sint Maarten',
 'Syria',
 'Eswatini',
 'Turks and Caicos Islands',
 'Chad',
 'French Southern Territories',
 'Togo',
 'Thailand',
 'Tajikistan',
 'Tokelau',
 'Timor Leste',
 'Turkmenistan',
 'Tunisia',
 'Tonga',
 'Turkey',
 'Trinidad and Tobago',
 'Tuvalu',
 'Taiwan',
 'Tanzania',
 'Ukraine',
 'Uganda',
 'United States Minor Outlying Islands',
 'United States',
 'Uruguay',
 'Uzbekistan',
 'Vatican',
 'Saint Vincent and the Grenadines',
 'Venezuela',
 'British Virgin Islands',
 'U.S. Virgin Islands',
 'Vietnam',
 'Vanuatu',
 'Wallis and Futuna',
 'Samoa',
 'Yemen',
 'Mayotte',
 'South Africa',
 'Zambia',
 'Zimbabwe']

In [27]:
import xml.etree.ElementTree as ET
from itertools import islice
timestep=-1

# for event, element in islice(ET.iterparse("rl_ai_conf.xml"),15):
for event, element in ET.iterparse(r"C:\Users\MehdiMoghadam\OneDrive - Agilysis Limited\Desktop\Data Collector\Sumo Map\Dashboard Ai Confrence\RL AL confrence\rl_ai_conf.xml"):
    if element.tag=="timestep":
        timestep = float(element.attrib["time"])
    elif element.tag == "vehicle":
        if timestep > -1:
            vals={"timestep":timestep}
            for att,val in element.items():
                try:
                    vals[att] = float(val)
                except:
                    vals[att] = val
            # do something with vals here

In [28]:
vals

{'timestep': 2999.0,
 'id': 'veh00000974',
 'eclass': 'HBEFA3/PC_G_EU4',
 'CO2': 0.0,
 'CO': 0.0,
 'HC': 0.0,
 'NOx': 0.0,
 'PMx': 0.0,
 'fuel': 0.0,
 'electricity': 0.0,
 'noise': 62.5,
 'route': '!veh00000974!var#1',
 'type': 'DEFAULT_VEHTYPE',
 'waiting': 0.0,
 'lane': 1720.0,
 'pos': 195.1,
 'speed': 13.36,
 'angle': 141.3,
 'x': 905.94,
 'y': 3152.61}